### PR TITLE
Active MQ Connector

### PR DESCRIPTION
**Pull request by mdemolsky**
Hi @alexsuter , @ivy-rew ,

could you please review my first connector. I created a Active MQ Connector to send and receive JMS by using the Active MQ Broker API.

Thanks for any feedback
Markus

### CODE REVIEW

**Comment by alexsuter** [comment]
Hey @mdemolsky 
I quickly tried to install the connector. But the installation is failing.
image

**Comment by mdemolsky** [comment]
I updated the meta.json, because there was a missing renaming of a dialog

**Comment by mdemolsky** [comment]
I updated the meta.json

**Comment by alexsuter** [comment]
This connector must be published to: https://github.com/axonivy-market/active-mq-connector

**Pull request closed without merging**
