### PR TITLE
Feature/xivy 5006 pimp todo demos

### PR DESCRIPTION
**Pull request by ivy-lli**

### CODE REVIEW

**Review by ivy-rew — APPROVED** [review]
fantastic: thanks for taking that burden

**Comment by ivy-rew** [comment]
I assume that the test must be adjusted? ... just starting the build to see.

**Comment by ivy-lli** [comment]
create event:
image

event list:
image

write email:
image

email list:
image

create task:
image

task list:
image

**Comment by ivy-rew** [comment]
Finally this connector is not just a pleasure due to it's technical capabilities, but for it's dialogs too :1st_place_medal:

**Pull request merged**
